services:

    loadbalancer:
        image: nginx:alpine
        container_name: lb-nginx
        ports:
            - "8080:8080"
        volumes:
            - ./docker/nginx/loadbalancer.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        depends_on:
            - app1
            - app2
            - app3
        networks:
            - ecommerce-network

    app1:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: laravel
                uid: 1000
        container_name: app-node-1
        expose:
            - "9000"
        environment:
            NODE_NAME: "Node-1"
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: ecommerce
            DB_USERNAME: laravel
            DB_PASSWORD: secret
            REDIS_HOST: redis
            REDIS_PORT: 6379
        volumes:
            - .:/var/www
        networks:
            - ecommerce-network

    app2:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: laravel
                uid: 1000
        container_name: app-node-2
        expose:
            - "9000"
        environment:
            NODE_NAME: "Node-2"
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: ecommerce
            DB_USERNAME: laravel
            DB_PASSWORD: secret
            REDIS_HOST: redis
            REDIS_PORT: 6379
        volumes:
            - .:/var/www
        networks:
            - ecommerce-network

    app3:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: laravel
                uid: 1000
        container_name: app-node-3
        expose:
            - "9000"
        environment:
            NODE_NAME: "Node-3"
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: ecommerce
            DB_USERNAME: laravel
            DB_PASSWORD: secret
            REDIS_HOST: redis
            REDIS_PORT: 6379
        volumes:
            - .:/var/www
        networks:
            - ecommerce-network

    mysql:
        image: mysql:8.0
        container_name: ecommerce-mysql
        environment:
            MYSQL_DATABASE: ecommerce
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - ecommerce-network

    redis:
        image: redis:alpine
        container_name: ecommerce-redis
        networks:
            - ecommerce-network

networks:
    ecommerce-network:
        driver: bridge

volumes:
    mysql-data:
