server {
    listen 8080;
    server_name app1;
    root /var/www/public;
    index index.php index.html;

    add_header X-Node "Node-1";

    client_max_body_size 2000M;
    keepalive_timeout 65;
    keepalive_requests 1000;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass app1:9000;
        fastcgi_keep_conn on;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
    charset utf-8;
}
